Реализовал приложения для терминала 1.19
htmlacademy-univer-nodejs-1/2219899-six-cities-3 pull request #2
Opened 2024-02-24 17:52 UTC by sxkxixx

2024-02-24 17:52 UTC, sxkxixx commented
@keksobot

2024-02-26 08:07 UTC, polRk requested changes

2024-02-26 08:07 UTC, polRk commented on src/cli/cli.application.ts
> +    if (Object.hasOwn(this.commandsMapping, command.getName())) {
Лучше использовать Map или WeakMap

2024-02-26 08:07 UTC, polRk commented on src/cli/commands/command.import.ts
> +    return this.parser.parse(readFileSync(fileName, 'utf-8'));
Тут стоит использовать стримы

2024-02-26 08:07 UTC, polRk commented on src/cli/commands/command.version.ts
> +    const packageJson = JSON.parse(readFileSync(resolve(this.packageJsonFileName), 'utf-8'));
Так работать не будет. Данный код показывает файл который лежит в месте запуск программы. Но этого файла может и не быть если вы итоговый бандл переместите или программа будет запущена из другой дирректории. Плюс тут нет проверок на ошибки.

стоит заиспользовать импорт json файла. Тогда бандлер включит json в финальный бандл и версия будет внутри вашей программы

2024-02-26 08:07 UTC, polRk commented on src/cli/common/parser/offer.parser.ts
> +      .map((row: string) => row.split('\t'))
Вам не нужно фильтровать, а затем делать маппинг по массиву дважды. Все можно поместить в один цикл

2024-02-26 08:07 UTC, polRk commented on src/main.js
Что это за файл?)

2024-02-26 09:20 UTC, sxkxixx commented
Внёс правки:
1. Удалил ненужный main.js
2. Переписал [замечание](https://github.com/htmlacademy-univer-nodejs-1/2219899-six-cities-3/pull/2#discussion_r1502182478) на 1 цикл + генератор
3. CLIApplication хранит обработчики команд в Map
4. Импорт package.json в код

2024-02-26 18:34 UTC, polRk commented on src/cli/cli.application.ts
> +    this.defaultCommand.process();
У вас не сответствует название функции с тем, что она выполняет. Вызов this.defaultCommand.process(); явно не попадает под описание

2024-02-26 18:36 UTC, polRk commented on src/cli/commands/command.import.ts
> +      for (const rent of this.parser.parse(readFileSync(fileName, 'utf-8'))) {
генератор хорошо. но вы все еще читаете файл целиком, и большие файлы не влезут в ОП. Нужно использовать stream

2024-02-26 18:36 UTC, polRk approved these changes
Необходимо использовать потоки при чтении файлов

2024-02-26 18:53 UTC, sxkxixx commented on src/cli/cli.application.ts
> +    this.defaultCommand.process();
Какое название метод наиболее подходящее?

2024-02-27 12:07 UTC, sxkxixx commented
Внёс правки:

1. TSV считывается потоком
2. Переименовал метод processUndefinedCommandMessage -> processDefaultCommand

2024-03-02 17:57 UTC, sxkxixx commented
@polRk 
Примите задание?

2024-03-05 06:20 UTC, polRk approved these changes
Хорошо сделали

2024-03-07 07:23 UTC, merged